# Generated by Django 2.2.6 on 2019-11-14 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20191011_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('reply', models.BooleanField(default=False)),
                ('coments', models.ManyToManyField(blank=True, to='api_users.CommentSkill')),
                ('cv', models.ForeignKey(on_delete=True, to='users.CV')),
                ('user_comment', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
