# Generated by Django 2.2.6 on 2019-10-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentskill',
            name='profile',
        ),
        migrations.AlterField(
            model_name='commentskill',
            name='coments',
            field=models.ManyToManyField(blank=True, to='api_users.CommentSkill'),
        ),
        migrations.AlterField(
            model_name='commentskill',
            name='cv',
            field=models.ForeignKey(on_delete=True, to='users.CV'),
        ),
        migrations.AlterField(
            model_name='commentskill',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
