# Generated by Django 2.2.6 on 2019-11-18 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_users', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentslikes',
            name='user',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentskill',
            name='coments',
            field=models.ManyToManyField(blank=True, to='api_users.CommentSkill'),
        ),
        migrations.AddField(
            model_name='commentskill',
            name='cv',
            field=models.ForeignKey(on_delete=True, to='users.CV'),
        ),
        migrations.AddField(
            model_name='commentskill',
            name='user_comment',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
