# Generated by Django 2.2.6 on 2019-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_auto_20191011_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentskill',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
