# Generated by Django 2.2.6 on 2019-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191011_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_cv_porter',
            field=models.BooleanField(default=False),
        ),
    ]
